### PR TITLE
[app] Two-phase build for app server

### PR DESCRIPTION
**Pull request by caervs**
To simplify onboarding, add a multi-phase Dockerfile for the app server.
Developers can now get ramped up with `docker-compose up`.

### CODE REVIEW

**Comment by kristiehoward** [comment]
LGTM

**Comment by kristiehoward** [comment]
LGTM

**Comment by kristiehoward** [comment]
LGTM

**Comment by kristiehoward** [comment]
LGTM

**Comment by caervs** [comment]
I'm gonna just merge this to make our tests green.

**Pull request merged**
